version: '3'

services:
  api: 
    image: node:14.15.3
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
      - ./package.json:/app/package.json
    env_file:
      - ./.docker.env
    depends_on:
      - db
      - redis
    links:
      - email-server
      - db
      - redis
    networks:
      - backend

  email-server:
    image: node:14.15.3
    command: sh -c "npm install && npm run start:dev"
    working_dir: /email-services
    volumes:
      -  ../email-service/:/email-services
      - ../email-service/package.json:/email-services/package.json
    hostname: email
    env_file:
      - ../email-service/.docker.env
    networks:
      - backend
  db:
    image: mysql:5.7
    ports:
      - '5432:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mock_project
    networks:
      - backend

  redis:
    restart: always
    image: redis
    container_name: redis_local
    command: redis-server --port 6380 
    ports:
    - "6380:6380"
    networks:
      - backend
networks:
  backend:
    driver: bridge
